public enum Scene
{
    EntryScene,
    MainMenu,
    GameplayEntryScene,
    GameplayExitScene,
    GameplayVictoryScene,
    GameplayDefeatScene,
    RandomisedScene,
    CatchAllScene,
    AbilityScene,
    ForestCliffScene,
    HealingScene,
    ForestValleyScene,
    ForestClearingScene,
    ForestDensScene,
    RuneScene,
    Zone1IntroductionScene,
    Zone2IntroductionScene,
    Zone3IntroductionScene
}
